Repository lichtblick-suite/asam-osi-converter, pull requests merged in 2025-01, with the labels that each got.

#60 Update CHANGELOG for new release
  CHANGELOG.md
  package-lock.json
  yarn.lock
Labels: documentation

#64 fix: rotation angles
  common/utils/geometry.ts
  common/utils/marker.ts
  package.json
  src/index.ts
  src/trafficlights/index.ts
  src/trafficsigns/index.ts
Labels: bug

#65 fix: lane boundaries without z-values
  common/utils/marker.ts
  src/index.ts
Labels: bug

#70 docs: create README.md for traffic sign images
  assets/images/README.md
Labels: documentation

#72 fix: split up and fix frame transforms, increase robustness
  src/index.ts
Labels: enhancement, cleanup
