Repository lichtblick-suite/asam-osi-converter, pull requests merged in 2025-05, with the labels that each got.

#100 feat: add options for cache and object axes
  src/index.ts
Labels: enhancement

#101 fix: mirror textures and traffic sign values
  src/__tests__/trafficsigns.spec.ts
  src/trafficlights/geometries.ts
  src/trafficsigns/geometries.ts
  src/trafficsigns/index.ts
  src/trafficsigns/textures.ts
Labels: bug, critical

#102 build: bump to v0.0.6, update package locks, update workflow versions
  .github/workflows/release.yaml
  package-lock.json
  package.json
  yarn.lock
Labels: documentation
